apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1 # Number of replicas for high availability
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: endouwashere/ds-frontend-service:18.0
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
