apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-upload-service
  template:
    metadata:
      labels:
        app: video-upload-service
    spec:
      # Init container: waits for Mongo to listen on port 27017
      initContainers:
      - name: wait-for-mongodb
        image: alpine:3.18
        command: ["/bin/sh","-c"]
        args:
          - apk add --no-cache netcat-openbsd;
            echo "Waiting for mongodb-service to be ready on port 27017...";
            until nc -z mongodb-service 27017; do
              echo "MongoDB not up yet, sleeping...";
              sleep 2;
            done;
            echo "MongoDB is up! Proceeding...";
      # Main container
      containers:
      - name: video-upload-service
        image: endouwashere/ds-video-upload-service:7.0
        ports:
          - containerPort: 8001
        env:
          - name: MONGO_URL
            value: "mongodb://mongodb-service:27017/video_status"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
